### ISSUE TITLE
能更新一下2020年的题库吗？

### ISSUE THREAD

**Issue by Olvi73** [PrintNow/ITKC#1]
链接: https://pan.baidu.com/s/1i5UQ4Y33-so636rX8TtpwA 提取码: ITKC 
这是2020年题库的链接
题库的排版格式大概是这样的
![image](https://user-images.githubusercontent.com/46037012/94253398-dccecf00-ff57-11ea-9db2-b18d17d68af8.png)

**Comment by PrintNow** [comment]
@Olvi73 好的，我尽量这几天弄一下

**Comment by PrintNow** [comment]
@Olvi73 已经更新，很抱歉鸽了那么久，最近在忙一些准备比赛的事情，基本没怎么空，刚好今天有时间，就去更新了下
